### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by zhangxgu** [ZhendongWang6/DIRE#1]
Nice work!
Is there any plan for code release?
Thanks!

**Comment by ShengwuZheng** [comment]
I have read your paper which is very impressive. So when do you prepare to release the code and dataset? I am waiting...

**Comment by hbchen121** [comment]
Front row, waiting for code release...

**Comment by zhongjian1999** [comment]
I have a question when I reading this paper. The reconstruct result is different from the input which is a real picture. But in the section 5.4 "RECONSTRUCTION FROM LATENT SPACE"  of DDIM paper, I think which is the same process in DIRE, the reconstruction error reported is low.  It makes me confusing and hope someone to discuss.

**Comment by zhongjian1999** [comment]
And the code of reconstruction based on DDIM can refer to a notebook. https://aistudio.baidu.com/aistudio/projectdetail/5279888

**Comment by zhongjian1999** [comment]
> I have a question when I reading this paper. The reconstruct result is different from the input which is a real picture. But in the section 5.4 "RECONSTRUCTION FROM LATENT SPACE" of DDIM paper, I think which is the same process in DIRE, the reconstruction error reported is low. It makes me confusing and hope someone to discuss.

And the code of reconstruction based on DDIM can refer to a notebook. https://aistudio.baidu.com/aistudio/projectdetail/5279888#:~:text=with%202%20Axes%3E-,%E5%9B%BE%E5%83%8F%E9%87%8D%E5%BB%BA,-%E5%9C%A8%20DDIM%20%E8%AE%BA%E6%96%87

**Comment by santaboi** [comment]
Still waiting for the dataset to be released , PLZ

**Comment by ZhendongWang6** [comment]
We have released our code, model, and dataset just now. Welcome to use them.
