### ISSUE TITLE
compute_dire.py questions

### ISSUE THREAD

**Issue by whitebeacon** [ZhendongWang6/DIRE#19]
<img width="1188" alt="6f0b1a979fb025eb7a1c93e1d596d78" src="https://github.com/ZhendongWang6/DIRE/assets/94464722/3e96c814-cee9-43f8-8f92-d21ecd40c78d">
Does any body know how to solve this problem?

**Comment by ciodar** [comment]
The weights you're loading are incorrect for the architecture. You have to configure the Unet parameters so that they match the weights you want to load.

**Comment by whitebeacon** [comment]
> The weights you're loading are incorrect for the architecture. You have to configure the Unet parameters so that they match the weights you want to load.

Hello, I modified images_dir, recons_dir, dire_dir and model_path in the compute_dire.py file and modified these into my own paths, and no other code was changed. After running compute_dire.py, then come out this question, Did you perform any other operations during debugging?How to configure the Unet parameters?

**Comment by ciodar** [comment]
It depends on the model checkpoint. For LSUN-bedroom I am using the lsun_bedroom.pt checkpoint released with the ADM [repository](https://github.com/openai/guided-diffusion). In that repo you can verify what are the needed configuration for each checkpoint.
If you are using `compute_dire.sh` you can directly modify the MODEL_FLAGS variable, otherwise you need to insert them into the configuration dictionary accordingly.
For example, this is the configuration for LSUN-Bedroom:
```
attention_resolutions 32,16,8 
class_cond False 
diffusion_steps 1000 
dropout 0.1 
image_size 256 
learn_sigma True 
noise_schedule linear 
num_channels 256 
num_head_channels 64 
num_res_blocks 2 
resblock_updown True 
use_fp16 True 
use_scale_shift_norm True
```

**Comment by whitebeacon** [comment]
> configuration

hi,sorry to bother you,I changed the parameters according to the given configuration and added images to the folder indicated by 'images_ dir',but no images have been generated in the folder indicated by 'recons_dir' and 'dire_dir'. Why is this?
<img width="1185" alt="1700215702775" src="https://github.com/ZhendongWang6/DIRE/assets/94464722/6d9293cb-7a61-4d6f-a37b-0703e9ac79f5">

**Comment by whitebeacon** [comment]
> It depends on the model checkpoint. For LSUN-bedroom I am using the lsun_bedroom.pt checkpoint released with the ADM [repository](https://github.com/openai/guided-diffusion). In that repo you can verify what is the needed configuration for each checkpoint. If you are using `compute_dire.sh` you can directly modify the MODEL_FLAGS variable, otherwise you need to insert them into the configuration dictionary accordingly. For example, this is the configuration for LSUN-Bedroom:
> 
> ```
> attention_resolutions 32,16,8 
> class_cond False 
> diffusion_steps 1000 
> dropout 0.1 
> image_size 256 
> learn_sigma True 
> noise_schedule linear 
> num_channels 256 
> num_head_channels 64 
> num_res_blocks 2 
> resblock_updown True 
> use_fp16 True 
> use_scale_shift_norm True
> ```

hi,sorry to bother you,I changed the parameters according to the given configuration and added images to the folder indicated by 'images_ dir',but no images have been generated in the folder indicated by 'recons_dir' and 'dire_dir'. Why is this?
![Uploading 1700215702775.png…]()

**Comment by whitebeacon** [comment]
<img width="1185" alt="1700215702775" src="https://github.com/ZhendongWang6/DIRE/assets/94464722/e226de13-43b4-4a2c-8f95-fe3b4ca44cbe">

**Comment by whitebeacon** [comment]
Oh,I forget to modify the parameter 'num_samples'.After I changed 'num_samples' to the number of my images in that folder, this program can't be stopped.Why is it?

**Comment by whitebeacon** [comment]
Oh,I forget to modify the parameter 'num_samples'.After I changed 'num_samples' to the number of my images in that folder, this program can't be stopped.Why is it?
<img width="1202" alt="1700216940384" src="https://github.com/ZhendongWang6/DIRE/assets/94464722/299409a6-cc61-4a75-a540-fe796b754896">
