### ISSUE TITLE
About the code 

### ISSUE THREAD

**Issue by Stitchsong** [ZhendongWang6/DIRE#2]
Thank you for your excellent work on image forgery identification. The DIRE you proposed has very far-reaching reference significance for my research.
You have not released the code of this project, do you plan to disclose the code?
Thanks again!

**Comment by matt-sharp** [comment]
@ZhendongWang6  Any update about when the code will be released?

**Comment by jS5t3r** [comment]
Yes, I would like to compare your method with others.

**Comment by ZhendongWang6** [comment]
We have released our code, model, and dataset just now. Welcome to use them.
