### ISSUE TITLE
Download link invalid

### ISSUE THREAD

**Issue by guwangtu** [ZhendongWang6/DIRE#26]
When I tried to download the pretrained model and dataset, the following message was displayed.
This link has been deleted.
Sorry, access to this document has been removed. Please contact the person who shares it with you.

**Comment by sanketkheni01** [comment]
I am still facing the same issue. How you fixed it?

**Comment by guwangtu** [comment]
Previously I couldn't access any link, but now I can access [RecDrive (code: dire)](https://rec.ustc.edu.cn/share/ec980150-4615-11ee-be0a-eb822f25e070)].

**Comment by sanketkheni01** [comment]
Oh. Okay. I also able to get the links. btw I have one question. have been able to get good results from the models. When I tried the models it is not performing well on ai generated images.

**Comment by githuboflk** [comment]
> Previously I couldn't access any link, but now I can access [RecDrive (code: dire)](https://rec.ustc.edu.cn/share/ec980150-4615-11ee-be0a-eb822f25e070)].

I can't apply for an account on this website. Is there another way to get it? Thanks a million!

**Comment by Danki4** [comment]
@githuboflk Hello, I would like to ask if you have downloaded this dataset and checkpoints. If possible, could you please help me upload it to Google Cloud Drive and share it with me? I really need this dataset, and the link left by the author for downloading the dataset has expired. I am really at a loss, and I look forward to your reply
