### ISSUE TITLE
About the inversion and reconstruction process

### ISSUE THREAD

**Issue by magneto0124** [ZhendongWang6/DIRE#3]
Hello! I found your work quite interesting and inspiring, and I have a question about the procedure before calculating dire. 
In section 4.1, it mentioned that ADM is used as the reconstruction model, then how did you finish the inversion process, do you use any specific models or just do it by yourself?

**Comment by ZhendongWang6** [comment]
We have released our code, model, and dataset just now. Welcome to use them.
